<a href="https://colab.research.google.com/github/Ridhijaisingh31/Internship/blob/main/CleaningData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('file1.csv')
df

print(df.isnull().sum())
print(df.dtypes)

Table                                             0
1. State & Type - Wise Number of Universities     4
Unnamed: 2                                       32
Unnamed: 3                                        1
Unnamed: 4                                       30
Unnamed: 5                                        9
Unnamed: 6                                       28
Unnamed: 7                                       20
Unnamed: 8                                       13
Unnamed: 9                                       32
Unnamed: 10                                      19
Unnamed: 11                                      27
Unnamed: 12                                      17
Unnamed: 13                                       1
dtype: int64
Table                                            object
1. State & Type - Wise Number of Universities    object
Unnamed: 2                                       object
Unnamed: 3                                       object
Unnamed: 4                                       object
Unnamed: 5                                       object
Unnamed: 6                                       object
Unnamed: 7                                       object
Unnamed: 8                                       object
Unnamed: 9                                       object
Unnamed: 10                                      object
Unnamed: 11                                      object
Unnamed: 12                                      object
Unnamed: 13                                      object
dtype: object

In [ ]:
df

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
2,Andhra Pradesh,NaN,NaN,1,1,20,1,NaN,NaN,NaN,1,NaN,4,28
3,Arunachal Pradesh,1,NaN,1,NaN,NaN,NaN,NaN,4,1,1,NaN,NaN,8
4,Assam,2,NaN,2,NaN,10,NaN,1,4,NaN,NaN,NaN,NaN,19
5,Bihar,2,NaN,3,NaN,14,1,1,NaN,NaN,1,NaN,NaN,22
6,Chandigarh,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,1,NaN,NaN,3
7,Chhatisgarh,1,NaN,2,NaN,11,NaN,1,7,NaN,NaN,NaN,NaN,22
8,Delhi,4,1,4,1,6,NaN,NaN,NaN,NaN,7,2,1,26
9,Goa,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
10,Gujarat,1,NaN,2,NaN,25,NaN,1,18,NaN,NaN,1,1,49
11,Haryana,1,NaN,1,NaN,14,NaN,NaN,16,NaN,2,NaN,3,37
12,Himachal Pradesh,1,NaN,2,NaN,4,NaN,NaN,17,NaN,NaN,NaN,NaN,24
13,Jammu and Kashmir,2,NaN,1,NaN,7,1,NaN,NaN,NaN,NaN,NaN,NaN,11
14,Jharkhand,1,NaN,1,NaN,7,NaN,NaN,2,NaN,1,NaN,1,13
15,Karnataka,1,NaN,1,NaN,25,NaN,1,8,NaN,4,NaN,11,51
16,Kerala,1,NaN,3,NaN,12,NaN,NaN,NaN,NaN,2,NaN,NaN,18
17,Madhya Pradesh,2,NaN,7,NaN,17,NaN,1,13,NaN,1,NaN,NaN,41
18,Maharashtra,1,NaN,3,NaN,19,NaN,1,NaN,NaN,7,2,12,45
19,Manipur,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
20,Meghalaya,1,NaN,1,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,10
21,Mizoram,1,NaN,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,3
22,Nagaland,1,NaN,1,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,4
23,Odisha,1,NaN,3,NaN,12,NaN,NaN,3,NaN,NaN,NaN,2,21
24,Puducherry,1,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4
25,Punjab,1,NaN,4,NaN,8,NaN,NaN,9,NaN,1,NaN,1,24
26,Rajasthan,1,NaN,3,NaN,19,NaN,1,32,NaN,NaN,NaN,8,64
27,Sikkim,1,NaN,1,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,7
28,Tamil Nadu,2,NaN,6,1,20,NaN,1,NaN,NaN,NaN,2,26,58
29,Telangana,3,NaN,2,NaN,11,1,1,NaN,NaN,NaN,NaN,2,20
30,Tripura,1,NaN,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,3
31,Uttar Pradesh,4,NaN,5,NaN,23,1,1,20,NaN,2,3,4,63
32,Uttrakhand,1,NaN,3,NaN,8,NaN,1,10,NaN,1,1,1,26
33,West Bengal,1,NaN,5,NaN,22,NaN,1,1,NaN,NaN,NaN,1,31
34,All India,43,1,75,3,316,5,13,181,1,32,11,79,760
35,"In UTs of , Andaman & Nicobar Islands, Dadra ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

DROPPING NA VALUES

In [ ]:
df1 = df.dropna()
df1

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
34,All India,43,1,75,3,316,5,13,181,1,32,11,79,760

DROPPING THE DUPLICATE VALUES

In [ ]:
df2 = df.drop_duplicates()
df2

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
34,All India,43,1,75,3,316,5,13,181,1,32,11,79,760

from matplotlib import pyplot as plt
import seaborn as sns
df2.groupby('Table').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df2.groupby('1. State & Type - Wise Number of Universities').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df2.groupby('Unnamed: 2').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df2.groupby('Unnamed: 3').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['1. State & Type - Wise Number of Universities'].value_counts()
    for x_label, grp in df2.groupby('Table')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Table')
_ = plt.ylabel('1. State & Type - Wise Number of Universities')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Unnamed: 2'].value_counts()
    for x_label, grp in df2.groupby('1. State & Type - Wise Number of Universities')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('1. State & Type - Wise Number of Universities')
_ = plt.ylabel('Unnamed: 2')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Unnamed: 3'].value_counts()
    for x_label, grp in df2.groupby('Unnamed: 2')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Unnamed: 2')
_ = plt.ylabel('Unnamed: 3')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Unnamed: 4'].value_counts()
    for x_label, grp in df2.groupby('Unnamed: 3')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Unnamed: 3')
_ = plt.ylabel('Unnamed: 4')

In [ ]:
df3= df.isnull()
df3

SUBSTITUTING THE NULL VALUES BY DEFAULT METHOD, FOWARD FILL METHOD AND BACKWARD FILL METHOD.

In [ ]:
df4=df.fillna(0)
df4

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
34,All India,43,1,75,3,316,5,13,181,1,32,11,79,760

In [ ]:
df5 =df.fillna(method= 'ffill')
df5

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
34,All India,43,1,75,3,316,5,13,181,1,32,11,79,760

In [ ]:
df6=df.fillna(method='bfill')
df6

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
34,All India,43,1,75,3,316,5,13,181,1,32,11,79,760

In [ ]:
#storing the clean data
FILE1=df.to_csv('cleaned_file1.csv', index=False)

REPEATING THE SAME STEPS

In [ ]:
import pandas as pd
import numpy as np

Df = pd.read_csv('file2.csv')
Df

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
2,Andhra Pradesh,0,0,1,1,20,1,0,0,0,1,0,4,28
3,Arunachal Pradesh,1,0,1,0,0,0,0,5,1,1,0,0,9
4,Assam,2,0,2,1,11,0,1,4,0,0,0,0,21
5,Bihar,2,0,3,0,14,1,1,0,0,1,0,0,22
6,Chandigarh,0,0,1,0,1,0,0,0,0,1,0,0,3
7,Chhatisgarh,1,0,2,0,11,0,1,7,0,0,0,0,22
8,Delhi,4,1,4,1,6,0,0,0,0,7,2,1,26
9,Goa,0,0,1,0,1,0,0,0,0,0,0,0,2
10,Gujarat,1,0,2,1,28,0,1,22,0,0,1,1,57
11,Haryana,1,0,1,1,14,0,0,17,0,2,0,3,39
12,Himachal Pradesh,1,0,2,1,4,0,0,17,0,0,0,0,25
13,Jammu and Kashmir,2,0,1,0,7,1,0,0,0,0,0,0,11
14,Jharkhand,1,0,1,0,7,0,0,3,0,1,0,1,14
15,Karnataka,1,0,1,1,25,0,1,8,0,4,0,11,52
16,Kerala,1,0,3,1,13,0,0,0,0,2,0,0,20
17,Madhya Pradesh,2,0,7,0,18,0,1,14,0,1,0,0,43
18,Maharashtra,1,0,3,0,19,0,1,0,0,7,2,12,45
19,Manipur,2,0,1,1,0,0,0,0,0,0,0,0,4
20,Meghalaya,1,0,1,0,0,0,0,8,0,0,0,0,10
21,Mizoram,1,0,1,0,0,0,0,1,0,0,0,0,3
22,Nagaland,1,0,1,0,0,0,0,2,0,0,0,0,4
23,Odisha,1,0,3,0,12,0,0,3,0,0,0,2,21
24,Puducherry,1,0,2,0,0,0,0,0,0,0,0,1,4
25,Punjab,1,0,4,0,9,0,0,10,0,1,0,1,26
26,Rajasthan,1,0,3,1,22,0,1,34,0,0,0,8,70
27,Sikkim,1,0,1,0,0,0,0,5,0,0,0,0,7
28,Tamil Nadu,2,0,6,1,20,0,1,0,0,0,2,26,58
29,Telangana,3,0,2,0,12,1,1,0,0,0,0,2,21
30,Tripura,1,0,1,0,0,0,0,1,0,0,0,0,3
31,Uttar Pradesh,4,0,5,1,23,1,1,23,0,2,3,4,67
32,Uttrakhand,1,0,3,0,9,0,1,11,0,1,1,1,28
33,West Bengal,1,0,5,1,23,0,1,2,0,0,0,1,34
34,All India,43,1,75,13,329,5,13,197,1,32,11,79,799
35,"In UTs of , Andaman & Nicobar Islands, Dadra ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(Df.isnull().sum())
print(Df.dtypes)

Table                                            0
1. State & Type - Wise Number of Universities    1
Unnamed: 2                                       1
Unnamed: 3                                       1
Unnamed: 4                                       1
Unnamed: 5                                       1
Unnamed: 6                                       1
Unnamed: 7                                       1
Unnamed: 8                                       1
Unnamed: 9                                       1
Unnamed: 10                                      1
Unnamed: 11                                      1
Unnamed: 12                                      1
Unnamed: 13                                      1
dtype: int64
Table                                            object
1. State & Type - Wise Number of Universities    object
Unnamed: 2                                       object
Unnamed: 3                                       object
Unnamed: 4                                       object
Unnamed: 5                                       object
Unnamed: 6                                       object
Unnamed: 7                                       object
Unnamed: 8                                       object
Unnamed: 9                                       object
Unnamed: 10                                      object
Unnamed: 11                                      object
Unnamed: 12                                      object
Unnamed: 13                                      object
dtype: object

DROPPING NULL VALUES

In [ ]:
Df1 =Df.dropna()
Df1

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
2,Andhra Pradesh,0,0,1,1,20,1,0,0,0,1,0,4,28
3,Arunachal Pradesh,1,0,1,0,0,0,0,5,1,1,0,0,9
4,Assam,2,0,2,1,11,0,1,4,0,0,0,0,21
5,Bihar,2,0,3,0,14,1,1,0,0,1,0,0,22
6,Chandigarh,0,0,1,0,1,0,0,0,0,1,0,0,3
7,Chhatisgarh,1,0,2,0,11,0,1,7,0,0,0,0,22
8,Delhi,4,1,4,1,6,0,0,0,0,7,2,1,26
9,Goa,0,0,1,0,1,0,0,0,0,0,0,0,2
10,Gujarat,1,0,2,1,28,0,1,22,0,0,1,1,57
11,Haryana,1,0,1,1,14,0,0,17,0,2,0,3,39
12,Himachal Pradesh,1,0,2,1,4,0,0,17,0,0,0,0,25
13,Jammu and Kashmir,2,0,1,0,7,1,0,0,0,0,0,0,11
14,Jharkhand,1,0,1,0,7,0,0,3,0,1,0,1,14
15,Karnataka,1,0,1,1,25,0,1,8,0,4,0,11,52
16,Kerala,1,0,3,1,13,0,0,0,0,2,0,0,20
17,Madhya Pradesh,2,0,7,0,18,0,1,14,0,1,0,0,43
18,Maharashtra,1,0,3,0,19,0,1,0,0,7,2,12,45
19,Manipur,2,0,1,1,0,0,0,0,0,0,0,0,4
20,Meghalaya,1,0,1,0,0,0,0,8,0,0,0,0,10
21,Mizoram,1,0,1,0,0,0,0,1,0,0,0,0,3
22,Nagaland,1,0,1,0,0,0,0,2,0,0,0,0,4
23,Odisha,1,0,3,0,12,0,0,3,0,0,0,2,21
24,Puducherry,1,0,2,0,0,0,0,0,0,0,0,1,4
25,Punjab,1,0,4,0,9,0,0,10,0,1,0,1,26
26,Rajasthan,1,0,3,1,22,0,1,34,0,0,0,8,70
27,Sikkim,1,0,1,0,0,0,0,5,0,0,0,0,7
28,Tamil Nadu,2,0,6,1,20,0,1,0,0,0,2,26,58
29,Telangana,3,0,2,0,12,1,1,0,0,0,0,2,21
30,Tripura,1,0,1,0,0,0,0,1,0,0,0,0,3
31,Uttar Pradesh,4,0,5,1,23,1,1,23,0,2,3,4,67
32,Uttrakhand,1,0,3,0,9,0,1,11,0,1,1,1,28
33,West Bengal,1,0,5,1,23,0,1,2,0,0,0,1,34
34,All India,43,1,75,13,329,5,13,197,1,32,11,79,799

DROPPING DUPLICATE VALUES

In [ ]:
Df2 = Df.drop_duplicates()
Df2

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
2,Andhra Pradesh,0,0,1,1,20,1,0,0,0,1,0,4,28
3,Arunachal Pradesh,1,0,1,0,0,0,0,5,1,1,0,0,9
4,Assam,2,0,2,1,11,0,1,4,0,0,0,0,21
5,Bihar,2,0,3,0,14,1,1,0,0,1,0,0,22
6,Chandigarh,0,0,1,0,1,0,0,0,0,1,0,0,3
7,Chhatisgarh,1,0,2,0,11,0,1,7,0,0,0,0,22
8,Delhi,4,1,4,1,6,0,0,0,0,7,2,1,26
9,Goa,0,0,1,0,1,0,0,0,0,0,0,0,2
10,Gujarat,1,0,2,1,28,0,1,22,0,0,1,1,57
11,Haryana,1,0,1,1,14,0,0,17,0,2,0,3,39
12,Himachal Pradesh,1,0,2,1,4,0,0,17,0,0,0,0,25
13,Jammu and Kashmir,2,0,1,0,7,1,0,0,0,0,0,0,11
14,Jharkhand,1,0,1,0,7,0,0,3,0,1,0,1,14
15,Karnataka,1,0,1,1,25,0,1,8,0,4,0,11,52
16,Kerala,1,0,3,1,13,0,0,0,0,2,0,0,20
17,Madhya Pradesh,2,0,7,0,18,0,1,14,0,1,0,0,43
18,Maharashtra,1,0,3,0,19,0,1,0,0,7,2,12,45
19,Manipur,2,0,1,1,0,0,0,0,0,0,0,0,4
20,Meghalaya,1,0,1,0,0,0,0,8,0,0,0,0,10
21,Mizoram,1,0,1,0,0,0,0,1,0,0,0,0,3
22,Nagaland,1,0,1,0,0,0,0,2,0,0,0,0,4
23,Odisha,1,0,3,0,12,0,0,3,0,0,0,2,21
24,Puducherry,1,0,2,0,0,0,0,0,0,0,0,1,4
25,Punjab,1,0,4,0,9,0,0,10,0,1,0,1,26
26,Rajasthan,1,0,3,1,22,0,1,34,0,0,0,8,70
27,Sikkim,1,0,1,0,0,0,0,5,0,0,0,0,7
28,Tamil Nadu,2,0,6,1,20,0,1,0,0,0,2,26,58
29,Telangana,3,0,2,0,12,1,1,0,0,0,0,2,21
30,Tripura,1,0,1,0,0,0,0,1,0,0,0,0,3
31,Uttar Pradesh,4,0,5,1,23,1,1,23,0,2,3,4,67
32,Uttrakhand,1,0,3,0,9,0,1,11,0,1,1,1,28
33,West Bengal,1,0,5,1,23,0,1,2,0,0,0,1,34
34,All India,43,1,75,13,329,5,13,197,1,32,11,79,799
35,"In UTs of , Andaman & Nicobar Islands, Dadra ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

SUBSTITUTING THE NULL VALUES BY DEFAULT METHOD, FOWARD FILL METHOD AND BACKWARD FILL METHOD.

In [ ]:
Df3= Df.isnull()
Df3

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False,False
35,False,True,True,True,True,True,True,True,True,True,True,True,True,True

In [ ]:
Df4= Df.fillna(0)
Df4

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
2,Andhra Pradesh,0,0,1,1,20,1,0,0,0,1,0,4,28
3,Arunachal Pradesh,1,0,1,0,0,0,0,5,1,1,0,0,9
4,Assam,2,0,2,1,11,0,1,4,0,0,0,0,21
5,Bihar,2,0,3,0,14,1,1,0,0,1,0,0,22
6,Chandigarh,0,0,1,0,1,0,0,0,0,1,0,0,3
7,Chhatisgarh,1,0,2,0,11,0,1,7,0,0,0,0,22
8,Delhi,4,1,4,1,6,0,0,0,0,7,2,1,26
9,Goa,0,0,1,0,1,0,0,0,0,0,0,0,2
10,Gujarat,1,0,2,1,28,0,1,22,0,0,1,1,57
11,Haryana,1,0,1,1,14,0,0,17,0,2,0,3,39
12,Himachal Pradesh,1,0,2,1,4,0,0,17,0,0,0,0,25
13,Jammu and Kashmir,2,0,1,0,7,1,0,0,0,0,0,0,11
14,Jharkhand,1,0,1,0,7,0,0,3,0,1,0,1,14
15,Karnataka,1,0,1,1,25,0,1,8,0,4,0,11,52
16,Kerala,1,0,3,1,13,0,0,0,0,2,0,0,20
17,Madhya Pradesh,2,0,7,0,18,0,1,14,0,1,0,0,43
18,Maharashtra,1,0,3,0,19,0,1,0,0,7,2,12,45
19,Manipur,2,0,1,1,0,0,0,0,0,0,0,0,4
20,Meghalaya,1,0,1,0,0,0,0,8,0,0,0,0,10
21,Mizoram,1,0,1,0,0,0,0,1,0,0,0,0,3
22,Nagaland,1,0,1,0,0,0,0,2,0,0,0,0,4
23,Odisha,1,0,3,0,12,0,0,3,0,0,0,2,21
24,Puducherry,1,0,2,0,0,0,0,0,0,0,0,1,4
25,Punjab,1,0,4,0,9,0,0,10,0,1,0,1,26
26,Rajasthan,1,0,3,1,22,0,1,34,0,0,0,8,70
27,Sikkim,1,0,1,0,0,0,0,5,0,0,0,0,7
28,Tamil Nadu,2,0,6,1,20,0,1,0,0,0,2,26,58
29,Telangana,3,0,2,0,12,1,1,0,0,0,0,2,21
30,Tripura,1,0,1,0,0,0,0,1,0,0,0,0,3
31,Uttar Pradesh,4,0,5,1,23,1,1,23,0,2,3,4,67
32,Uttrakhand,1,0,3,0,9,0,1,11,0,1,1,1,28
33,West Bengal,1,0,5,1,23,0,1,2,0,0,0,1,34
34,All India,43,1,75,13,329,5,13,197,1,32,11,79,799
35,"In UTs of , Andaman & Nicobar Islands, Dadra ...",0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
Df5=Df.fillna(method='bfill')
Df5

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
2,Andhra Pradesh,0,0,1,1,20,1,0,0,0,1,0,4,28
3,Arunachal Pradesh,1,0,1,0,0,0,0,5,1,1,0,0,9
4,Assam,2,0,2,1,11,0,1,4,0,0,0,0,21
5,Bihar,2,0,3,0,14,1,1,0,0,1,0,0,22
6,Chandigarh,0,0,1,0,1,0,0,0,0,1,0,0,3
7,Chhatisgarh,1,0,2,0,11,0,1,7,0,0,0,0,22
8,Delhi,4,1,4,1,6,0,0,0,0,7,2,1,26
9,Goa,0,0,1,0,1,0,0,0,0,0,0,0,2
10,Gujarat,1,0,2,1,28,0,1,22,0,0,1,1,57
11,Haryana,1,0,1,1,14,0,0,17,0,2,0,3,39
12,Himachal Pradesh,1,0,2,1,4,0,0,17,0,0,0,0,25
13,Jammu and Kashmir,2,0,1,0,7,1,0,0,0,0,0,0,11
14,Jharkhand,1,0,1,0,7,0,0,3,0,1,0,1,14
15,Karnataka,1,0,1,1,25,0,1,8,0,4,0,11,52
16,Kerala,1,0,3,1,13,0,0,0,0,2,0,0,20
17,Madhya Pradesh,2,0,7,0,18,0,1,14,0,1,0,0,43
18,Maharashtra,1,0,3,0,19,0,1,0,0,7,2,12,45
19,Manipur,2,0,1,1,0,0,0,0,0,0,0,0,4
20,Meghalaya,1,0,1,0,0,0,0,8,0,0,0,0,10
21,Mizoram,1,0,1,0,0,0,0,1,0,0,0,0,3
22,Nagaland,1,0,1,0,0,0,0,2,0,0,0,0,4
23,Odisha,1,0,3,0,12,0,0,3,0,0,0,2,21
24,Puducherry,1,0,2,0,0,0,0,0,0,0,0,1,4
25,Punjab,1,0,4,0,9,0,0,10,0,1,0,1,26
26,Rajasthan,1,0,3,1,22,0,1,34,0,0,0,8,70
27,Sikkim,1,0,1,0,0,0,0,5,0,0,0,0,7
28,Tamil Nadu,2,0,6,1,20,0,1,0,0,0,2,26,58
29,Telangana,3,0,2,0,12,1,1,0,0,0,0,2,21
30,Tripura,1,0,1,0,0,0,0,1,0,0,0,0,3
31,Uttar Pradesh,4,0,5,1,23,1,1,23,0,2,3,4,67
32,Uttrakhand,1,0,3,0,9,0,1,11,0,1,1,1,28
33,West Bengal,1,0,5,1,23,0,1,2,0,0,0,1,34
34,All India,43,1,75,13,329,5,13,197,1,32,11,79,799
35,"In UTs of , Andaman & Nicobar Islands, Dadra ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
Df6= Df.fillna(method='bfill')
Df6

,Table,1. State & Type - Wise Number of Universities,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,State,Central University,Central Open University,Institute of National Importance,Others,State Public University,Institute under State Legislature Act,State Open University,State Private University,State Private Open University,Deemed University-Government,Deemed University-Government Aided,Deemed University-Private,Grand Total
1,1,2,3,4,5,6,7,8,9,10,11,12,13,14
2,Andhra Pradesh,0,0,1,1,20,1,0,0,0,1,0,4,28
3,Arunachal Pradesh,1,0,1,0,0,0,0,5,1,1,0,0,9
4,Assam,2,0,2,1,11,0,1,4,0,0,0,0,21
5,Bihar,2,0,3,0,14,1,1,0,0,1,0,0,22
6,Chandigarh,0,0,1,0,1,0,0,0,0,1,0,0,3
7,Chhatisgarh,1,0,2,0,11,0,1,7,0,0,0,0,22
8,Delhi,4,1,4,1,6,0,0,0,0,7,2,1,26
9,Goa,0,0,1,0,1,0,0,0,0,0,0,0,2
10,Gujarat,1,0,2,1,28,0,1,22,0,0,1,1,57
11,Haryana,1,0,1,1,14,0,0,17,0,2,0,3,39
12,Himachal Pradesh,1,0,2,1,4,0,0,17,0,0,0,0,25
13,Jammu and Kashmir,2,0,1,0,7,1,0,0,0,0,0,0,11
14,Jharkhand,1,0,1,0,7,0,0,3,0,1,0,1,14
15,Karnataka,1,0,1,1,25,0,1,8,0,4,0,11,52
16,Kerala,1,0,3,1,13,0,0,0,0,2,0,0,20
17,Madhya Pradesh,2,0,7,0,18,0,1,14,0,1,0,0,43
18,Maharashtra,1,0,3,0,19,0,1,0,0,7,2,12,45
19,Manipur,2,0,1,1,0,0,0,0,0,0,0,0,4
20,Meghalaya,1,0,1,0,0,0,0,8,0,0,0,0,10
21,Mizoram,1,0,1,0,0,0,0,1,0,0,0,0,3
22,Nagaland,1,0,1,0,0,0,0,2,0,0,0,0,4
23,Odisha,1,0,3,0,12,0,0,3,0,0,0,2,21
24,Puducherry,1,0,2,0,0,0,0,0,0,0,0,1,4
25,Punjab,1,0,4,0,9,0,0,10,0,1,0,1,26
26,Rajasthan,1,0,3,1,22,0,1,34,0,0,0,8,70
27,Sikkim,1,0,1,0,0,0,0,5,0,0,0,0,7
28,Tamil Nadu,2,0,6,1,20,0,1,0,0,0,2,26,58
29,Telangana,3,0,2,0,12,1,1,0,0,0,0,2,21
30,Tripura,1,0,1,0,0,0,0,1,0,0,0,0,3
31,Uttar Pradesh,4,0,5,1,23,1,1,23,0,2,3,4,67
32,Uttrakhand,1,0,3,0,9,0,1,11,0,1,1,1,28
33,West Bengal,1,0,5,1,23,0,1,2,0,0,0,1,34
34,All India,43,1,75,13,329,5,13,197,1,32,11,79,799
35,"In UTs of , Andaman & Nicobar Islands, Dadra ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#storing the clean data
FILE2=Df.to_csv('cleaned_file2.csv', index=False)

UPLOADING THE FILES FROM GOOGLE COLAB TO GIT HUB